other_configs:
  image_w: 224
  image_h: 224
  hidden_size: 768

model_config:
  xgen:
    image_encoder:
      type: vit
      params:
        random_init: True
        pretrained_model_name: google/vit-base-patch16-224
        do_pooling: false
        hidden_dropout_prob: 0.1
        add_pooling_layer: False
        do_patch_embeddings: False
        image_size:
        - ${other_configs.image_w}
        - ${other_configs.image_h}
        patch_size: 16
        hidden_dim: ${other_configs.hidden_size}
        pretrained_model: vit_base_patch16_224
        mlp_dim: 3072

    text_embeddings:
      type: xgen_text_embedding
      bert_model_name: bert-base-uncased
      max_position_embeddings: 128
      hidden_dim: ${other_configs.hidden_size}
      hidden_size: 768

    joint_encoder:
      type: vit
      params:
        random_init: True
        do_pooling: false
        hidden_dropout_prob: 0.1
        add_pooling_layer: False
        do_patch_embeddings: False
        num_hidden_layers: 12
        num_attention_heads: 12
        hidden_dim: ${other_configs.hidden_size}

    joint_decoder:
      type: vit
      params:
        random_init: True
        do_pooling: false
        hidden_dropout_prob: 0.1
        add_pooling_layer: False
        do_patch_embeddings: False
        num_hidden_layers: 6
        num_attention_heads: 12
        hidden_dim: ${other_configs.hidden_size}
