other_configs:
  image_w: 224
  image_h: 224
  hidden_size: 768

model_config:
  xgen:
    image_encoder:
      type: vit
      params:
        random_init: True
        pretrained_model_name: google/vit-base-patch16-224
        do_pooling: false
        hidden_dropout_prob: 0.1
        add_pooling_layer: False
        do_patch_embeddings: True
        image_size:
        - ${other_configs.image_w}
        - ${other_configs.image_h}
        patch_size: 16
        hidden_dim: ${other_configs.hidden_size}
        pretrained_model: vit_base_patch16_224

    text_encoder:
      type: transformer
      params:
        bert_model_name: bert-base-uncased
        hidden_size: ${other_configs.hidden_size}
        max_position_embeddings: 512
        num_hidden_layers: 12
        num_attention_heads: 12
        output_attentions: false
        output_hidden_states: false
        add_pooling_layer: False
        do_pooling: false


    joint_encoder:
      type: vit
      params:
        random_init: True
        do_pooling: false
        hidden_dropout_prob: 0.1
        add_pooling_layer: False
        add_patch_embeddings: False
        do_patch_embeddings: False
        num_hidden_layers: 1
        num_attention_heads: 1
        hidden_dim: ${other_configs.hidden_size}

    joint_decoder:
      type: vit
      params:
        random_init: True
        do_pooling: false
        hidden_dropout_prob: 0.1
        add_pooling_layer: False
        do_patch_embeddings: False
        num_hidden_layers: 1
        num_attention_heads: 1
        hidden_dim: ${other_configs.hidden_size}
