# includes:
# - ../projects/unit/configs/vqa2_dataset_cfg.yaml

model_config:
  uniter:
    do_pretraining: false
    tasks: hateful_memes
    heads:
      hateful_memes:
        type: mlp
        num_layers: 1
        freeze: false
        lr_multiplier: 10.0
        in_dim: 768
        hidden_size: 1536
        num_labels: 2
        pooler_name: bert_pooler
    losses:
      hateful_memes: cross_entropy
    text_embeddings:
      vocab_size: 28996

dataset_config:
  hateful_memes:
    return_features_info: true
    use_features: true
    use_images: false
    use_image_feature_masks: true
    processors:
      text_processor:
        type: uniter_text_tokenizer
        params:
          from_pretrained: bert-base-cased
          tokenizer_config:
            type: bert-base-cased
            params:
              do_lower_case: false
          mask_probability: 0
          max_seq_length: 60

optimizer:
  type: adam_w
  params:
    lr: 8e-5
    eps: 1e-8
    weight_decay: 0.01

scheduler:
  type: warmup_linear
  params:
    num_warmup_steps: 600
    num_training_steps: 5000

evaluation:
  metrics:
  - accuracy
  - binary_f1
  - roc_auc

training:
  batch_size: 512
  lr_scheduler: true
  # Don't forget to update schedule_attributes if you update this
  max_updates: 5000
  # early_stop:
  #   criteria: hateful_memes/accuracy
  #   minimize: false
