includes:
  - projects/xtransform/configs/defaults.yaml

model_config:
  xgen:
    losses:
    - cross_transformative_loss

evaluation:
  metrics:
  - type: xgen
    params: 
      save_dir: ${env.save_dir}

