includes:
  - projects/xtransform/configs/defaults.yaml

model_config:
  xgen:
    losses:
    - cross_transformative_loss

evaluation:
  metrics:
  - type: xgen
    params: 
      save_dir: ${env.save_dir}
      processors:
        text_processor:
          type: bert_tokenizer
          params:
            tokenizer_config:
              type: bert-base-uncased
              params:
                do_lower_case: true
            mask_probability: 0
            max_seq_length: 16


