dataset_config:
  masked_conceptual_captions_12:
    data_dir: ${env.data_dir}/datasets
    depth_first: false
    fast_read: false
    use_images: false
    use_features: true
    features:
      cc12/cc12m.tsv
    # annotations:
    #   train:
    #   - cc/defaults/annotations/train_all.npy
    #   val:
    #   - cc/defaults/annotations/val.npy
    #   test:
    #   - cc/defaults/annotations/val.npy
    max_features: 100
    two_sentence: true
    two_sentence_probability: -0.1
    false_caption: true
    false_caption_probability: 0.5
    use_image_feature_masks: false
    processors:
      # masked_token_processor:
      #   type: masked_token
      #   params:
      #     tokenizer_config:
      #       type: bert-base-uncased
      #       params:
      #         do_lower_case: true
      #     mask_probability: 0.15
      #     max_seq_length: 128
      # masked_region_processor:
      #   type: masked_region
      #   params:
      #     mask_probability: 0.15
      #     mask_region_probability: 0.90
      # transformer_bbox_processor:
      #     type: transformer_bbox
      #     params:
      #       bbox_key: bbox
      #       image_width_key: image_width
      #       image_height_key: image_height
      text_processor:
        type: bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: true
          mask_probability: 0
          max_seq_length: 16
      image_processor:
        type: torchvision_transforms
        params:
          transforms:
            - type: Resize
              params:
                size: [256, 256]
            - type: CenterCrop
              params:
                size: [224, 224]
            - ToTensor
            - GrayScaleTo3Channels
            - type: Normalize
              params:
                mean: [0.46777044, 0.44531429, 0.40661017]
                std: [0.12221994, 0.12145835, 0.14380469]
      # text_processor:
    return_features_info: false
    # Return OCR information
    use_ocr: false
    # Return spatial information of OCR tokens if present
    use_ocr_info: false
